### PR TITLE
alt tag replaced

### PR DESCRIPTION
**Pull request by BarathaAberathne**
### What

replaced incorrectly transformed alt="/> tag with alt=""/>

### How to review

check if char replacements are correct

### Who can review

@anyone

### CODE REVIEW

**Review by lindenmckenzie — CHANGES_REQUESTED** [review]
what happens if it's not an alt tag?

**Comment by BarathaAberathne** [comment]
> what happens if it's not an alt tag?

I've tested with adding following style tag with the img alt tag: alt="" style="border: 2px solid #ccc;" . this didn't reproduced the bug again.

**Comment by lindenmckenzie** [comment]
but if for example:

```testing```

**Comment by BarathaAberathne** [comment]
> but if for example:
> 
> `testing`

tested by creating a new collection with the above, style tag is converted correctly as style="". also approving,pdf generation and publishing is successful.

**Review by BarathaAberathne — COMMENTED** [review]
changed the replace tag to convert any unclosed quote tags.

**Review by lindenmckenzie — APPROVED** [review]

**Pull request merged**
